unpackaged/main/default/objects/Case/fields/Extended_Warranty__c.field-meta.xml
<CustomField>
    <fullName>Extended_Warranty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extended Warranty</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Product_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Date__c</fullName>
    <label>Product Purchase Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Product_Total_Warranty_Days__c.field-meta.xml
<CustomField>
    <fullName>Product_Total_Warranty_Days__c</fullName>
    <label>Product Total Warranty Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Warranty_Summary__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Summary__c</fullName>
    <label>Warranty Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/caseTriggerHandler.cls
public class caseTriggerHandler {
	
    public void warrantySummary(List<case> triggerNew, Map<Id, case> triggerNewMap){
        for(Case c : triggerNew){
        	String createdDate = DateTime.Now().format();
            c.Warranty_Summary__c = 'Product purchased on ' + c.Product_Purchase_Date__c + 'and case created on ' + createdDate + '.\n';
            c.Warranty_Summary__c += 'Warranty is for ' + c.Product_Total_Warranty_Days__c + ' days. \n';
            c.Warranty_Summary__c += 'Extended warranty: ' + c.Extended_Warranty__c + '\n';
            c.Warranty_Summary__c += 'Have a nice day!';
            
        }
    }
}